import _Table from "antd/es/table";
import _asyncToGenerator from "@babel/runtime/helpers/asyncToGenerator";
import _inheritsLoose from "@babel/runtime/helpers/inheritsLoose";
import _regeneratorRuntime from "@babel/runtime/regenerator";
import * as React from 'react';
import "./index.scss"; // import { Input } from '@alifd/next';

import { tableBody } from "../../api/pages";

// let  entityList = []
// const Child: React.FC<selfProps> = (props) => {
//   const { getShowClick, getUser } = props;
//   const {
//     itemList = {
//       entityName: 'student',
//       entity: [
//         {
//           apiName: 'name',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: 50,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'TEXT',
//           defaultUse: true,
//           name: '学生姓名',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'province',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: 'DROP_LIST',
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'SINGLE_CHOICE',
//           defaultUse: true,
//           name: '省份',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'city',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: 'DROP_LIST',
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'MULTI_CHOICE',
//           defaultUse: true,
//           name: '城市',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'age',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: 3,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'INTEGER',
//           defaultUse: true,
//           name: '年龄',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'birthday',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: true,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'DATE',
//           defaultUse: true,
//           name: '生日',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'graduated',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'BOOL',
//           defaultUse: true,
//           name: '已毕业',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'phone',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: 11,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '请输入手机号',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: true,
//             userMask: false,
//           },
//           columnType: 'PHONE',
//           defaultUse: true,
//           name: '联系方式',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'roomId',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: 'PROMPT_NOT_ALLOW',
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: 'room',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'RELATIONSHIP',
//           defaultUse: true,
//           name: '所属教室',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'roomAddress',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: 'address',
//             quoteObjectApiName: 'room',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'QUOTE',
//           defaultUse: true,
//           name: '所属教室',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'book',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'ITEM_REDUNDANCY',
//           defaultUse: true,
//           name: '拥有书本',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'studentFile',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: 3,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'FILE',
//           defaultUse: true,
//           name: '学生文件',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'position',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'GEO_POSITION',
//           defaultUse: true,
//           name: '位置',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'xuefei',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '0.0',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: 15,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: 2,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'MONEY',
//           defaultUse: true,
//           name: '学费',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'shengao',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '0.00',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: 15,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: 3,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'DECIMAL',
//           defaultUse: true,
//           name: '身高',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'l_time',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'TIME',
//           defaultUse: true,
//           name: '午餐时间',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'xuehao',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'AUTO_NO',
//           defaultUse: true,
//           name: '学号',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'webSite',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: 200,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'WEBSITE',
//           defaultUse: true,
//           name: '网址',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'email',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: 20,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '请输入邮箱',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: true,
//             userMask: false,
//           },
//           columnType: 'EMAIL',
//           defaultUse: true,
//           name: '邮箱',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'studentImage',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: 3,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'IMAGE',
//           defaultUse: true,
//           name: '学生图片',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'percent',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: 10,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: 2,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'PERCENT',
//           defaultUse: true,
//           name: '排名百分比',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'deleted',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'BOOL',
//           defaultUse: false,
//           name: '已删除',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'ownerId',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: 'PROMPT_NOT_ALLOW',
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: 'sys_user',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'RELATIONSHIP',
//           defaultUse: false,
//           name: '所属人',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'createBy',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: 'PROMPT_NOT_ALLOW',
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: 'sys_user',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'RELATIONSHIP',
//           defaultUse: false,
//           name: '创建人',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'id',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'ID',
//           defaultUse: true,
//           name: '主键',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'updateBy',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: 'PROMPT_NOT_ALLOW',
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: 'sys_user',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'RELATIONSHIP',
//           defaultUse: false,
//           name: '修改人',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'createAt',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: true,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'DATE',
//           defaultUse: false,
//           name: '创建时间',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'enabled',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: false,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'BOOL',
//           defaultUse: false,
//           name: '已启用',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//         {
//           apiName: 'updateAt',
//           columnConfig: {
//             bachCreateItem: false,
//             cascadingDeletionType: null,
//             computeType: null,
//             copyWidthParent: false,
//             createNoForExists: false,
//             defaultValue: '',
//             encrypted: false,
//             endUnMasked: null,
//             fileCount: null,
//             helpText: '',
//             imageCount: null,
//             maxLength: null,
//             multiChoiceType: null,
//             optionSetApiName: null,
//             placeHolder: '',
//             preUnMasked: null,
//             quoteColumnApiName: '',
//             quoteObjectApiName: '',
//             relationObjectApiName: '',
//             scale: null,
//             showTime: true,
//             singleChoiceType: null,
//             startNo: 0,
//             unique: false,
//             userMask: false,
//           },
//           columnType: 'DATE',
//           defaultUse: true,
//           name: '最后修改时间',
//           joinColumnApiName: '',
//           entityId: '0',
//           objectApiName: 'student',
//         },
//       ],
//       entityList:[],
//     },
//   } = props; //id用于查询列表的表头和表体
//   console.log('itemList', itemList);
//   const [entityList, setEntityList] = useState([])
//   function getLineData (type, text) {
//     switch (type) {
//       case 'SINGLE_CHOICE':
//         return <span>{text.name}</span>;
//       case 'MULTI_CHOICE':
//         text.map((item, index) => {
//           return <span>{item.name}</span>;
//         });
//       case 'BOOL':
//         return <span>{text ? '是' : '否'}</span>;
//       case 'GEO_POSITION':
//         return (
//           <div>
//             <span>经度：{text.lat}</span>
//             <span>纬度：{text.lng}</span>
//           </div>
//         );
//       default:
//         return text;
//     }
//   };
//   //获取column
//   const [columns, setColumns] = useState([]);
//   const getColumn = (entityList) => {
//     let arrColumn = [];
//     if (entityList && entityList.length > 0) {
//       entityList.forEach((col) => {
//         let obj = {
//           key: `${col.objectApiName}${col.entityId}_${col.apiName}`,
//           dataIndex: `${col.objectApiName}${col.entityId}_${col.apiName}`,
//           title: col.name,
//           render: (text, record, index) => <div>{getLineData(col.columnType, text)}</div>,
//         };
//         arrColumn.push(obj);
//       });
//       console.log('最后获取的表头', arrColumn);
//     } else {
//       console.log('初始没有数据');
//     }
//     // setColumns(arrColumn);
//     return arrColumn
//   };
//   //获取表体
//   const [dataSource, setDataSource] = useState([]);
//   const getTable = async () => {
//     let queryColumns = [];
//     itemList.entityList.forEach((i) => {
//       let obj = {
//         objectApiName: i.objectApiName,
//         columnApiName: i.apiName,
//         joinColumnApiName: i.joinColumnApiName,
//         entityId: i.entityId,
//       };
//       queryColumns.push(obj);
//     });
//     // console.log('itemList2222222', itemList);
//     let data = {
//       queryColumns,
//       mainObjectApiName: itemList.entityName,
//       pageNo: 0,
//       pageSize: 10,
//     };
//     const res = await tableBody(data);
//     console.log('查询表格内容', res.data);
//     let arrTable = res.data.data;
//     arrTable.map((item, index) => {
//       item.key = index + '';
//     });
//     console.log(arrTable);
//     setDataSource(arrTable);
//   };
//   useEffect(() => {
//     // setEntityList(itemList.entityList)
//     // entityList = JSON.parse(JSON.stringify(itemList.entityList))
//     console.log('拖拽了table');
//     setColumns(getColumn(itemList.entityList));
//     getTable();
//   }, []);
//   // getColumn();
//   // getTable();
//   return (
//     <div>
//       <Table dataSource={dataSource} columns={columns} />;
//     </div>
//   );
// };
var Child = /*#__PURE__*/function (_React$Component) {
  _inheritsLoose(Child, _React$Component);

  function Child(props) {
    var _this;

    _this = _React$Component.call(this, props) || this;
    _this.state = {
      dataSource: [],
      columns: []
    };
    return _this;
  }

  var _proto = Child.prototype;

  _proto.componentDidMount = function componentDidMount() {
    this.getColumn();
  };

  _proto.getColumn = function getColumn() {
    var arrColumn = [];
    var itemList = this.props.itemList;

    if (itemList.entityList && itemList.entityList.length > 0) {
      itemList.entityList.forEach(function (col) {
        var obj = {
          key: "" + col.objectApiName + col.entityId + "_" + col.apiName,
          dataIndex: "" + col.objectApiName + col.entityId + "_" + col.apiName,
          title: col.name,
          render: function render(text, record, index) {
            return /*#__PURE__*/React.createElement("div", null, getLineData(col.columnType, text));
          }
        };
        arrColumn.push(obj);
      });
      console.log('最后获取的表头', arrColumn);
    } else {
      console.log('初始没有数据');
    } // setColumns(arrColumn);


    this.getTable();
    this.setState({
      columns: arrColumn
    });
  } //获取表体
  ;

  _proto.getTable =
  /*#__PURE__*/
  function () {
    var _getTable = _asyncToGenerator( /*#__PURE__*/_regeneratorRuntime.mark(function _callee() {
      var queryColumns, data, res, arrTable;
      return _regeneratorRuntime.wrap(function _callee$(_context) {
        while (1) {
          switch (_context.prev = _context.next) {
            case 0:
              queryColumns = [];
              this.props.itemList.entityList.forEach(function (i) {
                var obj = {
                  objectApiName: i.objectApiName,
                  columnApiName: i.apiName,
                  joinColumnApiName: i.joinColumnApiName,
                  entityId: i.entityId
                };
                queryColumns.push(obj);
              }); // console.log('itemList2222222', itemList);

              data = {
                queryColumns: queryColumns,
                mainObjectApiName: this.props.itemList.entityName.apiName,
                pageNo: 0,
                pageSize: 10
              };
              _context.next = 5;
              return tableBody(data);

            case 5:
              res = _context.sent;
              console.log('查询表格内容', res.data);
              arrTable = res.data.data;
              arrTable.map(function (item, index) {
                item.key = index + '';
              });
              console.log(arrTable);
              this.setState({
                dataSource: arrTable
              });

            case 11:
            case "end":
              return _context.stop();
          }
        }
      }, _callee, this);
    }));

    function getTable() {
      return _getTable.apply(this, arguments);
    }

    return getTable;
  }();

  _proto.render = function render() {
    var _this$state = this.state,
        columns = _this$state.columns,
        dataSource = _this$state.dataSource;
    return /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement(_Table, {
      dataSource: dataSource,
      columns: columns
    }), ";");
  };

  return Child;
}(React.Component);

Child.defaultProps = {
  itemList: {
    entityName: 'student',
    entity: [{
      apiName: 'name',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: 50,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'TEXT',
      defaultUse: true,
      name: '学生姓名',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'province',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: 'DROP_LIST',
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'SINGLE_CHOICE',
      defaultUse: true,
      name: '省份',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'city',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: 'DROP_LIST',
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'MULTI_CHOICE',
      defaultUse: true,
      name: '城市',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'age',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: 3,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'INTEGER',
      defaultUse: true,
      name: '年龄',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'birthday',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: true,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'DATE',
      defaultUse: true,
      name: '生日',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'graduated',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'BOOL',
      defaultUse: true,
      name: '已毕业',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'phone',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: 11,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '请输入手机号',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: true,
        userMask: false
      },
      columnType: 'PHONE',
      defaultUse: true,
      name: '联系方式',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'roomId',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: 'PROMPT_NOT_ALLOW',
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: 'room',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'RELATIONSHIP',
      defaultUse: true,
      name: '所属教室',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'roomAddress',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: 'address',
        quoteObjectApiName: 'room',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'QUOTE',
      defaultUse: true,
      name: '所属教室',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'book',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'ITEM_REDUNDANCY',
      defaultUse: true,
      name: '拥有书本',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'studentFile',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: 3,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'FILE',
      defaultUse: true,
      name: '学生文件',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'position',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'GEO_POSITION',
      defaultUse: true,
      name: '位置',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'xuefei',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '0.0',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: 15,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: 2,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'MONEY',
      defaultUse: true,
      name: '学费',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'shengao',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '0.00',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: 15,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: 3,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'DECIMAL',
      defaultUse: true,
      name: '身高',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'l_time',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'TIME',
      defaultUse: true,
      name: '午餐时间',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'xuehao',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'AUTO_NO',
      defaultUse: true,
      name: '学号',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'webSite',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: 200,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'WEBSITE',
      defaultUse: true,
      name: '网址',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'email',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: 20,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '请输入邮箱',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: true,
        userMask: false
      },
      columnType: 'EMAIL',
      defaultUse: true,
      name: '邮箱',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'studentImage',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: 3,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'IMAGE',
      defaultUse: true,
      name: '学生图片',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'percent',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: 10,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: 2,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'PERCENT',
      defaultUse: true,
      name: '排名百分比',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'deleted',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'BOOL',
      defaultUse: false,
      name: '已删除',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'ownerId',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: 'PROMPT_NOT_ALLOW',
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: 'sys_user',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'RELATIONSHIP',
      defaultUse: false,
      name: '所属人',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'createBy',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: 'PROMPT_NOT_ALLOW',
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: 'sys_user',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'RELATIONSHIP',
      defaultUse: false,
      name: '创建人',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'id',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'ID',
      defaultUse: true,
      name: '主键',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'updateBy',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: 'PROMPT_NOT_ALLOW',
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: 'sys_user',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'RELATIONSHIP',
      defaultUse: false,
      name: '修改人',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'createAt',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: true,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'DATE',
      defaultUse: false,
      name: '创建时间',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'enabled',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'BOOL',
      defaultUse: false,
      name: '已启用',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }, {
      apiName: 'updateAt',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: true,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'DATE',
      defaultUse: true,
      name: '最后修改时间',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student'
    }],
    entityList: [{
      apiName: 'name',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: 50,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'TEXT',
      defaultUse: true,
      name: '学生姓名',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '学生姓名'
    }, {
      apiName: 'province',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: 'DROP_LIST',
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'SINGLE_CHOICE',
      defaultUse: true,
      name: '省份',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '省份'
    }, {
      apiName: 'city',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: 'DROP_LIST',
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'MULTI_CHOICE',
      defaultUse: true,
      name: '城市',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '城市'
    }, {
      apiName: 'age',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: 3,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'INTEGER',
      defaultUse: true,
      name: '年龄',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '年龄'
    }, {
      apiName: 'birthday',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: true,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'DATE',
      defaultUse: true,
      name: '生日',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '生日'
    }, {
      apiName: 'graduated',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'BOOL',
      defaultUse: true,
      name: '已毕业',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '已毕业'
    }, {
      apiName: 'phone',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: 11,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '请输入手机号',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: true,
        userMask: false
      },
      columnType: 'PHONE',
      defaultUse: true,
      name: '联系方式',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '联系方式'
    }, {
      apiName: 'roomId',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: 'PROMPT_NOT_ALLOW',
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: 'room',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'RELATIONSHIP',
      defaultUse: true,
      name: '所属教室',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '所属教室'
    }, {
      apiName: 'roomAddress',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: 'address',
        quoteObjectApiName: 'room',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'QUOTE',
      defaultUse: true,
      name: '所属教室',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '所属教室'
    }, {
      apiName: 'book',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'ITEM_REDUNDANCY',
      defaultUse: true,
      name: '拥有书本',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '拥有书本'
    }, {
      apiName: 'studentFile',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: 3,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'FILE',
      defaultUse: true,
      name: '学生文件',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '学生文件'
    }, {
      apiName: 'position',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'GEO_POSITION',
      defaultUse: true,
      name: '位置',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '位置'
    }, {
      apiName: 'xuefei',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '0.0',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: 15,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: 2,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'MONEY',
      defaultUse: true,
      name: '学费',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '学费'
    }, {
      apiName: 'shengao',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '0.00',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: 15,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: 3,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'DECIMAL',
      defaultUse: true,
      name: '身高',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '身高'
    }, {
      apiName: 'l_time',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'TIME',
      defaultUse: true,
      name: '午餐时间',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '午餐时间'
    }, {
      apiName: 'xuehao',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'AUTO_NO',
      defaultUse: true,
      name: '学号',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '学号'
    }, {
      apiName: 'webSite',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: 200,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'WEBSITE',
      defaultUse: true,
      name: '网址',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '网址'
    }, {
      apiName: 'email',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: 20,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '请输入邮箱',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: true,
        userMask: false
      },
      columnType: 'EMAIL',
      defaultUse: true,
      name: '邮箱',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '邮箱'
    }, {
      apiName: 'studentImage',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: 3,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'IMAGE',
      defaultUse: true,
      name: '学生图片',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '学生图片'
    }, {
      apiName: 'percent',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: 10,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: 2,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'PERCENT',
      defaultUse: true,
      name: '排名百分比',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '排名百分比'
    }, {
      apiName: 'deleted',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'BOOL',
      defaultUse: false,
      name: '已删除',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '已删除'
    }, {
      apiName: 'ownerId',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: 'PROMPT_NOT_ALLOW',
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: 'sys_user',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'RELATIONSHIP',
      defaultUse: false,
      name: '所属人',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '所属人'
    }, {
      apiName: 'createBy',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: 'PROMPT_NOT_ALLOW',
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: 'sys_user',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'RELATIONSHIP',
      defaultUse: false,
      name: '创建人',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '创建人'
    }, {
      apiName: 'id',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'ID',
      defaultUse: true,
      name: '主键',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '主键'
    }, {
      apiName: 'updateBy',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: 'PROMPT_NOT_ALLOW',
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: 'sys_user',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'RELATIONSHIP',
      defaultUse: false,
      name: '修改人',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '修改人'
    }, {
      apiName: 'createAt',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: true,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'DATE',
      defaultUse: false,
      name: '创建时间',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '创建时间'
    }, {
      apiName: 'enabled',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: false,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'BOOL',
      defaultUse: false,
      name: '已启用',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '已启用'
    }, {
      apiName: 'updateAt',
      columnConfig: {
        bachCreateItem: false,
        cascadingDeletionType: null,
        computeType: null,
        copyWidthParent: false,
        createNoForExists: false,
        defaultValue: '',
        encrypted: false,
        endUnMasked: null,
        fileCount: null,
        helpText: '',
        imageCount: null,
        maxLength: null,
        multiChoiceType: null,
        optionSetApiName: null,
        placeHolder: '',
        preUnMasked: null,
        quoteColumnApiName: '',
        quoteObjectApiName: '',
        relationObjectApiName: '',
        scale: null,
        showTime: true,
        singleChoiceType: null,
        startNo: 0,
        unique: false,
        userMask: false
      },
      columnType: 'DATE',
      defaultUse: true,
      name: '最后修改时间',
      joinColumnApiName: '',
      entityId: '0',
      objectApiName: 'student',
      tableName: '最后修改时间'
    }]
  }
};
export default Child;