import * as React from 'react';
import { createElement, useEffect } from 'react';
import './index.scss';

// import { Input } from '@alifd/next';

import { Modal, Button, Popconfirm, Tooltip, message } from 'antd';

import { useState } from 'react';

import Bus from '../../utils/eventBus';

// type selfProps = {
//   getShow: Function;
//   getUser: Function;
// };

export interface ColorfulDialogProps {
  key: React.Key;
  name: string;
  age: number;
  address: string;
  visible?: boolean;
}

class ColorfulDialog extends React.Component {
  static defaultProps = {
    itemList: {
      entityName: 'student',
      entity: [
        {
          apiName: 'name',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: 50,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'TEXT',
          defaultUse: true,
          name: '学生姓名',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'province',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: 'DROP_LIST',
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'SINGLE_CHOICE',
          defaultUse: true,
          name: '省份',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'city',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: 'DROP_LIST',
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'MULTI_CHOICE',
          defaultUse: true,
          name: '城市',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'age',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: 3,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'INTEGER',
          defaultUse: true,
          name: '年龄',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'birthday',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: true,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'DATE',
          defaultUse: true,
          name: '生日',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'graduated',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'BOOL',
          defaultUse: true,
          name: '已毕业',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'phone',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: 11,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '请输入手机号',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: true,
            userMask: false,
          },
          columnType: 'PHONE',
          defaultUse: true,
          name: '联系方式',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'roomId',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: 'PROMPT_NOT_ALLOW',
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: 'room',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'RELATIONSHIP',
          defaultUse: true,
          name: '所属教室',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'roomAddress',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: 'address',
            quoteObjectApiName: 'room',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'QUOTE',
          defaultUse: true,
          name: '所属教室',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'book',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'ITEM_REDUNDANCY',
          defaultUse: true,
          name: '拥有书本',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'studentFile',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: 3,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'FILE',
          defaultUse: true,
          name: '学生文件',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'position',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'GEO_POSITION',
          defaultUse: true,
          name: '位置',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'xuefei',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '0.0',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: 15,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: 2,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'MONEY',
          defaultUse: true,
          name: '学费',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'shengao',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '0.00',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: 15,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: 3,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'DECIMAL',
          defaultUse: true,
          name: '身高',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'l_time',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'TIME',
          defaultUse: true,
          name: '午餐时间',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'xuehao',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'AUTO_NO',
          defaultUse: true,
          name: '学号',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'webSite',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: 200,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'WEBSITE',
          defaultUse: true,
          name: '网址',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'email',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: 20,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '请输入邮箱',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: true,
            userMask: false,
          },
          columnType: 'EMAIL',
          defaultUse: true,
          name: '邮箱',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'studentImage',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: 3,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'IMAGE',
          defaultUse: true,
          name: '学生图片',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'percent',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: 10,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: 2,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'PERCENT',
          defaultUse: true,
          name: '排名百分比',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'deleted',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'BOOL',
          defaultUse: false,
          name: '已删除',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'ownerId',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: 'PROMPT_NOT_ALLOW',
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: 'sys_user',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'RELATIONSHIP',
          defaultUse: false,
          name: '所属人',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'createBy',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: 'PROMPT_NOT_ALLOW',
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: 'sys_user',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'RELATIONSHIP',
          defaultUse: false,
          name: '创建人',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'id',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'ID',
          defaultUse: true,
          name: '主键',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'updateBy',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: 'PROMPT_NOT_ALLOW',
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: 'sys_user',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'RELATIONSHIP',
          defaultUse: false,
          name: '修改人',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'createAt',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: true,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'DATE',
          defaultUse: false,
          name: '创建时间',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'enabled',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'BOOL',
          defaultUse: false,
          name: '已启用',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
        {
          apiName: 'updateAt',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: true,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'DATE',
          defaultUse: true,
          name: '最后修改时间',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
        },
      ],
      entityList: [
        {
          apiName: 'name',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: 50,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'TEXT',
          defaultUse: true,
          name: '学生姓名',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '学生姓名',
        },
        {
          apiName: 'province',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: 'DROP_LIST',
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'SINGLE_CHOICE',
          defaultUse: true,
          name: '省份',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '省份',
        },
        {
          apiName: 'city',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: 'DROP_LIST',
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'MULTI_CHOICE',
          defaultUse: true,
          name: '城市',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '城市',
        },
        {
          apiName: 'age',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: 3,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'INTEGER',
          defaultUse: true,
          name: '年龄',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '年龄',
        },
        {
          apiName: 'birthday',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: true,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'DATE',
          defaultUse: true,
          name: '生日',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '生日',
        },
        {
          apiName: 'graduated',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'BOOL',
          defaultUse: true,
          name: '已毕业',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '已毕业',
        },
        {
          apiName: 'phone',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: 11,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '请输入手机号',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: true,
            userMask: false,
          },
          columnType: 'PHONE',
          defaultUse: true,
          name: '联系方式',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '联系方式',
        },
        {
          apiName: 'roomId',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: 'PROMPT_NOT_ALLOW',
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: 'room',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'RELATIONSHIP',
          defaultUse: true,
          name: '所属教室',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '所属教室',
        },
        {
          apiName: 'roomAddress',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: 'address',
            quoteObjectApiName: 'room',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'QUOTE',
          defaultUse: true,
          name: '所属教室',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '所属教室',
        },
        {
          apiName: 'book',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'ITEM_REDUNDANCY',
          defaultUse: true,
          name: '拥有书本',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '拥有书本',
        },
        {
          apiName: 'studentFile',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: 3,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'FILE',
          defaultUse: true,
          name: '学生文件',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '学生文件',
        },
        {
          apiName: 'position',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'GEO_POSITION',
          defaultUse: true,
          name: '位置',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '位置',
        },
        {
          apiName: 'xuefei',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '0.0',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: 15,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: 2,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'MONEY',
          defaultUse: true,
          name: '学费',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '学费',
        },
        {
          apiName: 'shengao',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '0.00',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: 15,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: 3,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'DECIMAL',
          defaultUse: true,
          name: '身高',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '身高',
        },
        {
          apiName: 'l_time',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'TIME',
          defaultUse: true,
          name: '午餐时间',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '午餐时间',
        },
        {
          apiName: 'xuehao',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'AUTO_NO',
          defaultUse: true,
          name: '学号',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '学号',
        },
        {
          apiName: 'webSite',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: 200,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'WEBSITE',
          defaultUse: true,
          name: '网址',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '网址',
        },
        {
          apiName: 'email',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: 20,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '请输入邮箱',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: true,
            userMask: false,
          },
          columnType: 'EMAIL',
          defaultUse: true,
          name: '邮箱',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '邮箱',
        },
        {
          apiName: 'studentImage',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: 3,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'IMAGE',
          defaultUse: true,
          name: '学生图片',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '学生图片',
        },
        {
          apiName: 'percent',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: 10,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: 2,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'PERCENT',
          defaultUse: true,
          name: '排名百分比',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '排名百分比',
        },
        {
          apiName: 'deleted',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'BOOL',
          defaultUse: false,
          name: '已删除',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '已删除',
        },
        {
          apiName: 'ownerId',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: 'PROMPT_NOT_ALLOW',
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: 'sys_user',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'RELATIONSHIP',
          defaultUse: false,
          name: '所属人',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '所属人',
        },
        {
          apiName: 'createBy',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: 'PROMPT_NOT_ALLOW',
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: 'sys_user',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'RELATIONSHIP',
          defaultUse: false,
          name: '创建人',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '创建人',
        },
        {
          apiName: 'id',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'ID',
          defaultUse: true,
          name: '主键',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '主键',
        },
        {
          apiName: 'updateBy',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: 'PROMPT_NOT_ALLOW',
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: 'sys_user',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'RELATIONSHIP',
          defaultUse: false,
          name: '修改人',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '修改人',
        },
        {
          apiName: 'createAt',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: true,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'DATE',
          defaultUse: false,
          name: '创建时间',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '创建时间',
        },
        {
          apiName: 'enabled',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: false,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'BOOL',
          defaultUse: false,
          name: '已启用',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '已启用',
        },
        {
          apiName: 'updateAt',
          columnConfig: {
            bachCreateItem: false,
            cascadingDeletionType: null,
            computeType: null,
            copyWidthParent: false,
            createNoForExists: false,
            defaultValue: '',
            encrypted: false,
            endUnMasked: null,
            fileCount: null,
            helpText: '',
            imageCount: null,
            maxLength: null,
            multiChoiceType: null,
            optionSetApiName: null,
            placeHolder: '',
            preUnMasked: null,
            quoteColumnApiName: '',
            quoteObjectApiName: '',
            relationObjectApiName: '',
            scale: null,
            showTime: true,
            singleChoiceType: null,
            startNo: 0,
            unique: false,
            userMask: false,
          },
          columnType: 'DATE',
          defaultUse: true,
          name: '最后修改时间',
          joinColumnApiName: '',
          entityId: '0',
          objectApiName: 'student',
          tableName: '最后修改时间',
        },
      ],
    },
    actionList: [
      {
        "title": "按钮1",
        "actionList": [
          {
            "name": "onClick",
            "type": 0
          }
        ]
      },
      {
        "title": "按钮2",
        "actionList": [
          {
            "name": "onClick",
            "type": 0
          }
        ]
      }
    ]
    // isModalVisible: true
  };
  constructor(props) {
    super(props);

    console.log('constructor: props', props)
    this.state = {
      visible: props.visible,
    };
  }

  componentDidMount() {
    console.log('this.props', this.props)
    if (this.props.__designMode === 'design') {
      // 低代码编辑态中强制显示，将控制权交给引擎侧
      this.setState({
        visible: true
      })
    }
    Bus.addListener(this.props.id, (data) => {
      // console.log(22222222222222222,this.props.id, data);
      // console.log(this.props.id)

      // setVisible(data)
      this.setState({
        visible: data
      })
    });
  }

  componentWillReceiveProps(nextProps: Readonly<{}>, nextContext: any): void {
    this.setState({
      visible: nextProps.visible
    })
    // console.log('componentWillReceiveProps----this.props.id',nextProps.id)
    Bus.addListener(nextProps.id, (data) => {
      // console.log('componentWillReceiveProps',nextProps.id, data);
      // console.log(this.props.id)

      // setVisible(data)
      this.setState({
        visible: data.show
      })
    });
  }

  handleOk() {
    console.log('111112222');
    this.setState({
      visible: false
    })
  }

  handleCancel() {
    this.setState({
      visible: false
    })
  }

  //气泡确认框的操作
  confirmProp() {
    message.success('提交成功');
  };

  cancelProp() {
    message.error('取消提交');
  };

  testMessage(value) {
    console.log(value);

    const type = value[0].type;
    switch (type) {
      //
      case 0:
        break;
      case 1:
        let arr2 = [];
        value[0].actionDialogParamsList.forEach((i, index) => {
          let obj = {};
          obj.title = i.name;
          obj.key = i.name;
          obj.dataIndex = 'name';

          // console.log(obj);
          arr2.push(obj);
        });

        let columnsTest = arr2;

        setColumnsBtn(columnsTest);

        let arr3 = [];
        value[0].actionDialogParamsList.forEach((i, index) => {
          let obj = {};
          obj.name = i.name;

          obj.key = index;

          // console.log(obj);
          arr3.push(obj);
        });

        let dataTest3 = arr3;


        setTableDataBtn(dataTest3);

        setClickVisible(true);

        break;
      case 2:
        message.info(`${value[0].triggeredContent}`);
        break;
      case 4:
        let id = value[0].actionPage[value[0].actionPage.length - 1];
        window.location = `www.test.com?id=${id}`;
        break;
      case 5:

        // value[0].actionJSNamezheng
        value[0].actionJSValue()
        break;
      default:
        break;
    }
  }

  render() {
    const { children, actionList, footer } = this.props;
    const { visible } = this.state;
    return (
      <div>
        <Modal
          // title={dialogTitle}
          {...this.props}
          visible={visible}
          onOk={() => this.handleOk()}
          onCancel={() => this.handleCancel()}
          width={+this.props.width}
          footer={footer ? undefined : null}
        >
          {children}
        </Modal>
      </div>
    );
  }
}

export default ColorfulDialog;
