export declare function getPagesList(data: any): import("axios").AxiosPromise<any>;
export declare function addPages(data: any): import("axios").AxiosPromise<any>;
export declare function logPages(data: any): Promise<import("axios").AxiosResponse<any>>;
export declare function metaInfo(params: any): import("axios").AxiosPromise<any>;
export declare function dataTable(data: any): import("axios").AxiosPromise<any>;
export declare function tableBody(data: any): import("axios").AxiosPromise<any>;
export declare function tableBodyTree(data: any): import("axios").AxiosPromise<any>;
export declare function delData(mainObjectApiName: any, id: any): import("axios").AxiosPromise<any>;
export declare function delDataBatch(params: any): import("axios").AxiosPromise<any>;
export declare function enableData(data: any): import("axios").AxiosPromise<any>;
export declare function enableDataBatch(data: any): import("axios").AxiosPromise<any>;
