import * as React from 'react';
import './index.scss';
export interface ColorfulComplexProps {
    key: React.Key;
    name: string;
    age: number;
    address: string;
}
declare class Child extends React.Component {
    static defaultProps: {
        btnList: {
            title: string;
            actionList: {
                name: string;
                type: number;
            }[];
            functional: string;
        }[];
        itemList: {
            entityName: {
                apiName: string;
                desc: string;
                enabled: boolean;
                iconId: string;
                id: string;
                name: string;
                structure: string;
            };
            entity: ({
                apiName: string;
                columnConfig: {
                    bachCreateItem: boolean;
                    cascadingDeletionType: any;
                    computeType: any;
                    copyWidthParent: boolean;
                    createNoForExists: boolean;
                    defaultValue: string;
                    encrypted: boolean;
                    endUnMasked: any;
                    fileCount: any;
                    helpText: string;
                    imageCount: any;
                    maxLength: number;
                    multiChoiceType: any;
                    optionSetApiName: string;
                    placeHolder: string;
                    preUnMasked: any;
                    quoteColumnApiName: string;
                    quoteObjectApiName: string;
                    relationObjectApiName: string;
                    scale: any;
                    showTime: boolean;
                    singleChoiceType: any;
                    startNo: number;
                    unique: boolean;
                    userMask: boolean;
                };
                columnType: string;
                columnTypeGroup: string;
                defaultUse: boolean;
                name: string;
                mainEntityId: string;
                joinColumnApiName: string;
                entityId: string;
                objectApiName: string;
                index: number;
            } | {
                apiName: string;
                columnConfig: {
                    bachCreateItem: boolean;
                    cascadingDeletionType: any;
                    computeType: any;
                    copyWidthParent: boolean;
                    createNoForExists: boolean;
                    defaultValue: string;
                    encrypted: boolean;
                    endUnMasked: any;
                    fileCount: any;
                    helpText: string;
                    imageCount: any;
                    maxLength: any;
                    multiChoiceType: any;
                    optionSetApiName: string;
                    placeHolder: string;
                    preUnMasked: any;
                    quoteColumnApiName: string;
                    quoteObjectApiName: string;
                    relationObjectApiName: string;
                    scale: any;
                    showTime: boolean;
                    singleChoiceType: string;
                    startNo: number;
                    unique: boolean;
                    userMask: boolean;
                };
                columnType: string;
                columnTypeGroup: string;
                defaultUse: boolean;
                name: string;
                mainEntityId: string;
                joinColumnApiName: string;
                entityId: string;
                objectApiName: string;
                index: number;
            })[];
            entityList: ({
                apiName: string;
                columnConfig: {
                    bachCreateItem: boolean;
                    cascadingDeletionType: any;
                    computeType: any;
                    copyWidthParent: boolean;
                    createNoForExists: boolean;
                    defaultValue: string;
                    encrypted: boolean;
                    endUnMasked: any;
                    fileCount: any;
                    helpText: string;
                    imageCount: any;
                    maxLength: number;
                    multiChoiceType: any;
                    optionSetApiName: string;
                    placeHolder: string;
                    preUnMasked: any;
                    quoteColumnApiName: string;
                    quoteObjectApiName: string;
                    relationObjectApiName: string;
                    scale: any;
                    showTime: boolean;
                    singleChoiceType: any;
                    startNo: number;
                    unique: boolean;
                    userMask: boolean;
                };
                columnType: string;
                columnTypeGroup: string;
                defaultUse: boolean;
                name: string;
                mainEntityId: string;
                joinColumnApiName: string;
                entityId: string;
                objectApiName: string;
                index: number;
            } | {
                apiName: string;
                columnConfig: {
                    bachCreateItem: boolean;
                    cascadingDeletionType: any;
                    computeType: any;
                    copyWidthParent: boolean;
                    createNoForExists: boolean;
                    defaultValue: string;
                    encrypted: boolean;
                    endUnMasked: any;
                    fileCount: any;
                    helpText: string;
                    imageCount: any;
                    maxLength: any;
                    multiChoiceType: any;
                    optionSetApiName: string;
                    placeHolder: string;
                    preUnMasked: any;
                    quoteColumnApiName: string;
                    quoteObjectApiName: string;
                    relationObjectApiName: string;
                    scale: any;
                    showTime: boolean;
                    singleChoiceType: string;
                    startNo: number;
                    unique: boolean;
                    userMask: boolean;
                };
                columnType: string;
                columnTypeGroup: string;
                defaultUse: boolean;
                name: string;
                mainEntityId: string;
                joinColumnApiName: string;
                entityId: string;
                objectApiName: string;
                index: number;
            })[];
        };
        pagesList: any[];
    };
    constructor(props: any);
    componentDidMount(): void;
    componentWillReceiveProps(nextProps: any, preState: any): void;
    onSwitchChange(value: any, apiName: any): void;
    onCascaderChange(value: any): void;
    actionPageChange(value: any, option: any): void;
    render(): JSX.Element;
}
export default Child;
